### ISSUE TITLE
Chinese Open source Font ?

### ISSUE THREAD

**Issue by hugolpz** [clintonb/edx-fonts#1]
Hello Clinton,

Is your edx-fonts the by default font repository of EdX or an optional module ? 
Can I suggest you to integrate some specific Chinese fonts ?

**Comment by clintonb** [comment]
@hugolpz The official edX repo is located at https://github.com/edx/edx-fonts/. I believe only edx-analytics-dashboard uses these fonts. Post to edx-code to see if others are interested in adding additional fonts and changing the CDN for edx-platform.
